version: 2

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Only on tags formatted like v0.1.1
              only: /^v\d+\.\d+\.\d+$/

jobs:
  lint:
    docker:
      - image: golang:1.19
    working_directory: /go/src/github.com/skpr/cloudfront-cloudwatchlogs
    steps:
      - checkout
      - run: |
          go install golang.org/x/lint/golint@latest
          make lint

  test:
    docker:
      - image: golang:1.19
    working_directory: /go/src/github.com/skpr/cloudfront-cloudwatchlogs
    steps:
      - checkout
      - run: make test

  release:
    docker:
      - image: golang:1.19
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update && apt-get install -y zip
            go install github.com/tcnksm/ghr@latest
      - run:
          name: "Build"
          command: make package
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git describe --tags --always)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./function.zip
