name: ☁️ Publish Artifacts

on:
  push:
    tags:
      - v1.*

jobs:
  artifacts:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: 📦 Install Mise
        run: |
          curl https://mise.run | sh
          mise install

      - name: lint
        run: mise release
